// <auto-generated />
using System;
using AyehAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RifLearnAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614203326_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AyehAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Para empezar desde cero",
                            Name = "Básico",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Amplía tu vocabulario",
                            Name = "Intermedio",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Domina el tarifit",
                            Name = "Avanzado",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("AyehAPI.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 14, 20, 33, 24, 888, DateTimeKind.Utc).AddTicks(6176),
                            Description = "Aprende a saludar en tarifit",
                            Icon = "👋",
                            SortOrder = 1,
                            Title = "Saludos básicos"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 14, 20, 33, 24, 888, DateTimeKind.Utc).AddTicks(6188),
                            Description = "Miembros de la familia",
                            Icon = "👨‍👩‍👧",
                            SortOrder = 2,
                            Title = "Familia"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 14, 20, 33, 24, 888, DateTimeKind.Utc).AddTicks(6191),
                            Description = "Cuenta del 1 al 20",
                            Icon = "🔢",
                            SortOrder = 3,
                            Title = "Números 1-20"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 14, 20, 33, 24, 888, DateTimeKind.Utc).AddTicks(6194),
                            Description = "Los colores en tarifit",
                            Icon = "🎨",
                            SortOrder = 1,
                            Title = "Colores"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 14, 20, 33, 24, 888, DateTimeKind.Utc).AddTicks(6198),
                            Description = "Animales comunes",
                            Icon = "🐾",
                            SortOrder = 2,
                            Title = "Animales"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 14, 20, 33, 24, 888, DateTimeKind.Utc).AddTicks(6202),
                            Description = "Alimentos y bebidas",
                            Icon = "🍲",
                            SortOrder = 3,
                            Title = "Comida"
                        });
                });

            modelBuilder.Entity("AyehAPI.Models.Progress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastStudiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("PercentageComplete")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "LessonId")
                        .IsUnique();

                    b.ToTable("Progresses");
                });

            modelBuilder.Entity("AyehAPI.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WrongOptions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "Hola",
                            LessonId = 1,
                            QuestionText = "¿Qué significa 'Azul' en rifeño?",
                            Type = 0,
                            WrongOptions = "Gracias|Familia|Agua"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "Tanemmirt",
                            LessonId = 1,
                            QuestionText = "¿Cómo se dice 'Gracias' en tarifit?",
                            Type = 0,
                            WrongOptions = "Azul|Aman|Labas"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = "Aman",
                            Hint = "Empieza por A",
                            LessonId = 1,
                            QuestionText = "_____ significa 'Agua' en español.",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = "Wakha",
                            LessonId = 1,
                            QuestionText = "¿Cómo se dice 'De nada' en tarifit?",
                            Type = 0,
                            WrongOptions = "Rjak|Samḥ|Labas"
                        });
                });

            modelBuilder.Entity("AyehAPI.Models.QuizResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("AyehAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AyehAPI.Models.VocabItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExampleSentence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Spanish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tarifit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("VocabItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExampleSentence = "Azul, labas?",
                            LessonId = 1,
                            Spanish = "Hola",
                            Tarifit = "Azul"
                        },
                        new
                        {
                            Id = 2,
                            ExampleSentence = "Akka, a zin!",
                            LessonId = 1,
                            Spanish = "Adiós",
                            Tarifit = "Akka"
                        },
                        new
                        {
                            Id = 3,
                            ExampleSentence = "Azul! Labas?",
                            LessonId = 1,
                            Spanish = "¿Cómo estás?",
                            Tarifit = "Labas?"
                        },
                        new
                        {
                            Id = 4,
                            ExampleSentence = "Labas, tanemmirt",
                            LessonId = 1,
                            Spanish = "Bien",
                            Tarifit = "Labas"
                        },
                        new
                        {
                            Id = 5,
                            ExampleSentence = "Tanemmirt, a gma",
                            LessonId = 1,
                            Spanish = "Gracias",
                            Tarifit = "Tanemmirt"
                        },
                        new
                        {
                            Id = 6,
                            ExampleSentence = "Wakha, ur illi walu",
                            LessonId = 1,
                            Spanish = "De nada",
                            Tarifit = "Wakha"
                        },
                        new
                        {
                            Id = 7,
                            ExampleSentence = "Rjak, ini yas",
                            LessonId = 1,
                            Spanish = "Por favor",
                            Tarifit = "Rjak"
                        },
                        new
                        {
                            Id = 8,
                            ExampleSentence = "Samḥ iyi, a gma",
                            LessonId = 1,
                            Spanish = "Perdona",
                            Tarifit = "Samḥ"
                        },
                        new
                        {
                            Id = 9,
                            ExampleSentence = "Baba inu d ameqqran",
                            LessonId = 2,
                            Spanish = "Padre",
                            Tarifit = "Baba"
                        },
                        new
                        {
                            Id = 10,
                            ExampleSentence = "Yemma inu tessen arifen",
                            LessonId = 2,
                            Spanish = "Madre",
                            Tarifit = "Yemma"
                        },
                        new
                        {
                            Id = 11,
                            ExampleSentence = "Gma inu d amzyan",
                            LessonId = 2,
                            Spanish = "Hermano",
                            Tarifit = "Gma"
                        },
                        new
                        {
                            Id = 12,
                            ExampleSentence = "Ultma inu tga tamɣart",
                            LessonId = 2,
                            Spanish = "Hermana",
                            Tarifit = "Ultma"
                        },
                        new
                        {
                            Id = 13,
                            ExampleSentence = "Tawacult inu d tamqqrant",
                            LessonId = 2,
                            Spanish = "Familia",
                            Tarifit = "Tawacult"
                        },
                        new
                        {
                            Id = 14,
                            LessonId = 3,
                            Spanish = "Uno",
                            Tarifit = "Yan"
                        },
                        new
                        {
                            Id = 15,
                            LessonId = 3,
                            Spanish = "Dos",
                            Tarifit = "Sin"
                        },
                        new
                        {
                            Id = 16,
                            LessonId = 3,
                            Spanish = "Tres",
                            Tarifit = "Kraḍ"
                        },
                        new
                        {
                            Id = 17,
                            LessonId = 3,
                            Spanish = "Cuatro",
                            Tarifit = "Kkuẓ"
                        },
                        new
                        {
                            Id = 18,
                            LessonId = 3,
                            Spanish = "Cinco",
                            Tarifit = "Semmus"
                        },
                        new
                        {
                            Id = 19,
                            LessonId = 3,
                            Spanish = "Diez",
                            Tarifit = "Mraw"
                        },
                        new
                        {
                            Id = 20,
                            LessonId = 3,
                            Spanish = "Veinte",
                            Tarifit = "Ţţamraw"
                        });
                });

            modelBuilder.Entity("AyehAPI.Models.Lesson", b =>
                {
                    b.HasOne("AyehAPI.Models.Category", "Category")
                        .WithMany("Lessons")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AyehAPI.Models.Progress", b =>
                {
                    b.HasOne("AyehAPI.Models.Lesson", "Lesson")
                        .WithMany("Progresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyehAPI.Models.User", "User")
                        .WithMany("Progresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AyehAPI.Models.Question", b =>
                {
                    b.HasOne("AyehAPI.Models.Lesson", "Lesson")
                        .WithMany("Questions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("AyehAPI.Models.QuizResult", b =>
                {
                    b.HasOne("AyehAPI.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyehAPI.Models.User", "User")
                        .WithMany("QuizResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AyehAPI.Models.VocabItem", b =>
                {
                    b.HasOne("AyehAPI.Models.Lesson", "Lesson")
                        .WithMany("VocabItems")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("AyehAPI.Models.Category", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("AyehAPI.Models.Lesson", b =>
                {
                    b.Navigation("Progresses");

                    b.Navigation("Questions");

                    b.Navigation("VocabItems");
                });

            modelBuilder.Entity("AyehAPI.Models.User", b =>
                {
                    b.Navigation("Progresses");

                    b.Navigation("QuizResults");
                });
#pragma warning restore 612, 618
        }
    }
}
